## Numpy

In [1]:
import numpy as np

In [4]:
List1 = [1,2,3,4]
nparray1 = np.array(List1)
print(nparray1)
type(nparray1)

[1 2 3 4]


numpy.ndarray

In [8]:
# Multi Dimensional Arrays
List1 = [1,2,3,4]
List2 = [5,6,7,8]

nparr = np.array( [ List1, List2 ] )
print(nparr)
print(nparr.shape)
print(nparr.size)
print(nparr.dtype)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
8
int32


In [11]:
# Generally, numpy is not used for storing string arrays, but you can do so.  
# It's the wrong tool for the job.  
L3 = ['Hello', 'How', 'are', 'you']
nparr = np.array(L3)
nparr.dtype  # unicode type

dtype('<U5')

In [12]:
# Create identity matrix 
np.identity(n=6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [14]:
np.ones(shape=[2,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.zeros(shape=[3,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## Array Indexing / Slicing

In [22]:
A1 = np.array( [1,2,3,4,5,6,7] )
A1[3:-1]  # Play around by changing the indexes

array([4, 5, 6])

In [23]:
A1[::2]

array([1, 3, 5, 7])

### Math Operations

In [24]:
A1 + 5

array([ 6,  7,  8,  9, 10, 11, 12])

In [67]:
A1 * 100

array([100, 200, 300, 400, 500, 600, 700])

In [68]:
np.sqrt(A1)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131])

In [26]:
demo = np.array([[1, 3,4,6,8], [1,5,8,9,7], [9,8,7,6,5]])
demo

array([[1, 3, 4, 6, 8],
       [1, 5, 8, 9, 7],
       [9, 8, 7, 6, 5]])

In [27]:
demo.transpose()

array([[1, 1, 9],
       [3, 5, 8],
       [4, 8, 7],
       [6, 9, 6],
       [8, 7, 5]])

In [28]:
demo.mean()

5.8

In [70]:
np.sum(demo, axis=1)

array([22, 30, 35])

In [66]:
print(demo)
print( np.max(demo) )  # np.min
print( np.std(demo, axis=1) )

[[1 3 4 6 8]
 [1 5 8 9 7]
 [9 8 7 6 5]]
9
[2.41660919 2.82842712 1.41421356]


In [71]:
V1 = demo[0]
V2 = demo[1]
np.dot(V1, V2)  # 1*1  +  3*5  +  4*8  +  6*9  +  8*7  == 158


158

### Reshaping

In [31]:
print(demo, '\n')

demo[1:, 1:4]  # demo[ rows, cols ]

[[1 3 4 6 8]
 [1 5 8 9 7]
 [9 8 7 6 5]] 



array([[5, 8, 9],
       [8, 7, 6]])

In [35]:
np.reshape(demo, newshape=[5,3])

array([[1, 3, 4],
       [6, 8, 1],
       [5, 8, 9],
       [7, 9, 8],
       [7, 6, 5]])

In [37]:
demo

array([[1, 3, 4, 6, 8],
       [1, 5, 8, 9, 7],
       [9, 8, 7, 6, 5]])

In [40]:
# Flatten column wise
print( np.ravel(demo, order='F') )

# Flatten row wise. 
print( np.ravel(demo, order='C') )
print( demo.flatten() )

[1 1 9 3 5 8 4 8 7 6 9 6 8 7 5]
[1 3 4 6 8 1 5 8 9 7 9 8 7 6 5]
[1 3 4 6 8 1 5 8 9 7 9 8 7 6 5]


### Concatenate

In [62]:
L0 = [1,2,3,4,5]
L1 = [10,20,30,40,50]
print(L0, L1)

A2 = np.concatenate( (L0, L1), axis=0)
print(A2)

[1, 2, 3, 4, 5] [10, 20, 30, 40, 50]
[ 1  2  3  4  5 10 20 30 40 50]


## Misc Operations (Optional)

In [43]:
print( np.fliplr(demo), '\n' )
print( np.flipud(demo) )

[[8 6 4 3 1]
 [7 9 8 5 1]
 [5 6 7 8 9]] 

[[9 8 7 6 5]
 [1 5 8 9 7]
 [1 3 4 6 8]]


In [47]:
np.rot90(demo, k=1)

array([[8, 7, 5],
       [6, 9, 6],
       [4, 8, 7],
       [3, 5, 8],
       [1, 1, 9]])

In [56]:
print( demo, '\n' )

print( np.roll(demo, shift=1, axis=0) , '\n')  # vertical axis

print( np.roll( demo, shift=2, axis=1) , '\n')  # horizontal axis 

[[1 3 4 6 8]
 [1 5 8 9 7]
 [9 8 7 6 5]] 

[[9 8 7 6 5]
 [1 3 4 6 8]
 [1 5 8 9 7]] 

[[6 8 1 3 4]
 [9 7 1 5 8]
 [6 5 9 8 7]] 

